### ISSUE TITLE
Create a config file

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/finite-fault-product#26]
Instead of assuming that the user has (for example) PDL installed in a particular location, let's set up a config file to hold all of that stuff.  Here's what PAGER's config looks like:
```
pdl:
  java: /usr/bin/java
  jarfile: /Users/user/ProductClient/ProductClient.jar
  privatekey: /Users/user/ProductClient/pager_dsa.pri
  configfile: /Users/user/ProductClient/config.ini
```
